# TASK 11: INTERACTIVE WEB DASHBOARD PROTOTYPE WITH MULTIPLE CHARTS
import streamlit as st
import pandas as pd
import os


st.set_page_config(page_title="E-Commerce Analyst Dashboard", layout="wide")

st.title("....E-Commerce Store Performance Dashboard....")


data_path = "../outputs/cleaned_ecommerce_data.csv"

if os.path.exists(data_path):
    df = pd.read_csv(data_path)
   
    # 1. CORE KPIs CALCULATION
    total_revenue = df[df['event_type'] == 'purchase']['price'].sum()
    total_purchases = df[df['event_type'] == 'purchase'].shape[0]
    aov = total_revenue / total_purchases if total_purchases > 0 else 0
    
    # Display Top KPI Cards
    col1, col2, col3 = st.columns(3)
    col1.metric(label="💰 Total Revenue", value=f"${total_revenue:,.2f}")
    col2.metric(label="📦 Total Orders Completed", value=f"{total_purchases:,}")
    col3.metric(label="🛍️ Average Order Value (AOV)", value=f"${aov:.2f}")
    
    st.markdown("---")
    
    
    # 2. CHARTS SECTION (BAR, PIE & LINE CHARTS)
    st.subheader("📈 Interactive Business Data Visualizations")
    
    chart_col1, chart_col2 = st.columns(2)
    
    with chart_col1:
        # A. BAR CHART: Top 5 Brands by Revenue
        st.markdown("#### 🏆 Top 5 Brands by Revenue")
        brand_data = df[df['event_type'] == 'purchase'].groupby('brand')['price'].sum().sort_values(ascending=False).head(5).reset_index()
        # Generating Interactive Streamlit Bar Chart
        st.bar_chart(data=brand_data, x='brand', y='price', color='#1f77b4', use_container_width=True)
        
    with chart_col2:
        # B. PIE CHART (Donut Style): Platform Events Breakdown
        st.markdown("#### 🔄 Platform User Actions Share")
        event_counts = df['event_type'].value_counts().reset_index()
        event_counts.columns = ['Action', 'Count']
        # Generating Interactive Donut Chart using Vega-Lite
        st.vega_lite_chart(event_counts, {
            'mark': {'type': 'arc', 'innerRadius': 50, 'tooltip': True},
            'encoding': {
                'theta': {'field': 'Count', 'type': 'quantitative'},
                'color': {'field': 'Action', 'type': 'nominal', 'scale': {'range': ['#2980b9', '#e67e22', '#27ae60']}}
            }
        }, use_container_width=True)

    st.markdown("---")
    
    # C. LINE CHART: Hourly Sales Trend Analysis
    st.markdown("#### 📅 Hourly Sales Trend Analysis")
    hourly_sales = df[df['event_type'] == 'purchase'].groupby('hour')['price'].sum().reset_index()
    st.line_chart(data=hourly_sales, x='hour', y='price', color='#e74c3c', use_container_width=True)

    st.markdown("---")
    
    # 3. CONVERSION FUNNEL & BUSINESS RECOMMENDATIONS
    col_chart, col_rec = st.columns([1, 1])
    
    with col_chart:
        st.subheader("🛒 User Conversion Funnel")
        # Displaying the static funnel chart generated by the backend
        funnel_img_path = "../outputs/funnel_chart.png"
        if os.path.exists(funnel_img_path):
            st.image(funnel_img_path, use_container_width=True)
        else:
            st.info("Failed to load Funnel Chart image from the outputs directory.")
            
    with col_rec:
        st.subheader("💡 Final Business Recommendations")
        st.error("**Friction Point:** A massive **90.92%** of users drop off after viewing products without adding them to the cart. Product Page UI/UX updates are highly critical to improve conversion.")
        st.warning("**Data Quality Risk:** A significant portion of revenue comes from unbranded products ('Unknown'). It is highly recommended to make the Brand Name field mandatory in the inventory system.")
        st.success("**Loyalty Program:** Since repeat users drive the vast majority of stable ecosystem actions and purchases, introducing targeted loyalty rewards will drastically boost retention.")
        
else:
    st.error("Data file not found. Please run the backend scripts inside the 'notebooks/' folder first to generate 'outputs/' datasets.")